### ISSUE TITLE
Support typed wildcard

### ISSUE THREAD

**Issue by borkdude** [bfontaine/grape#2]
Question: does `$&` also work with types? 

Example:

foo.clj:
``` clojure
(apply + 1 2 3 [4 5 6])
```

This works:

```
$ grape "(apply $symbol $number $&)" /tmp/foo.clj
1:(apply + 1 2 3 [4 5 6])
```

But it seems this doesn't:

```
 grape "(apply $symbol $number& $)" /tmp/foo.clj
```

**Comment by borkdude** [comment]
Ultimately I'd like to execute this query to get examples of using `reify` with more than one interface:

```
$ grape "(reify ($+ ($symbol ($* $list))"
```

Possibly the regex implementation from spec can be borrowed or even used accomplish this. Another alternative might be malli once it gets sequence schemas. (cc @ikitommi).

**Comment by bfontaine** [comment]
Hello @borkdude, no it doesn’t.

**Comment by borkdude** [comment]
@bfontaine I changed the title for this issue to "Support typed wildcard", e.g. `$vector&`. 

If you're interested in supporting spec-like regexes like `"($cat reify ($+ ($symbol ($* $list))"` let me know and I'll make another issue for that.

**Comment by bfontaine** [comment]
@borkdude Thanks. I’m not sure I want to support spec-like regexes since they have a very different format than currently-supported patterns. I’d prefer to work on something that would use spec itself if possible.

`grape`’s [matching pipeline](https://github.com/bfontaine/grape/blob/e6a4796cc5f28de446587fde318d60c43e0dc95d/src/grape/core.clj#L29-L33) is quite simple: `tree-seq` the code, and filter subtrees using a pattern. If we can write a function that takes a tree and a spec and is able to tell if the tree matches the spec, we’ll have our implementation.

You can open a separate issue so we can discuss there.

**Comment by borkdude** [comment]
Feel free to close this if you don't think this fits with grape.

**Comment by bfontaine** [comment]
I do think this fits with grape, and just added it 😉

**Comment by borkdude** [comment]
Thanks!
